server.port=8080
firebase.project-id=minutes-of-meeting-df929
firebase.credentials=classpath:serviceAccountKey.json
app.jwt.secret=ChangeThisToALongRandomSecretKeyForMinutesOfMeetingApp2026!
app.jwt.expiration-ms=86400000
